### ISSUE TITLE
Remove packetio.Read/Write without context.Context?

### ISSUE THREAD

**Issue by at-wat** [pion/transport#107]
https://github.com/pion/transport/pull/104 adds ReadContext/WriteContext.
Ordinary Read/Write is remained to keep compatibility with Go1's `io.Reader/Writer`.
After migrating all codes in pion/webrtc and pion/srtp, Read/Write might be able to be removed, but it will drop compatibility with `io.Reader/Writer`.

If you have opinions to this, please add comments.

**Comment by jech** [comment]
I've mentioned previously my opinion that Context doesn't belong in a low-level library.  The main point of context is propagation; in circumstances where propagation is not needed, lighter primitives (such as Set*Readline) are more appropriate.

Please do not bake context into the transport's libraries API; doing that will impair optimisation later on.

**Comment by Sean-Der** [comment]
Resolving since we removed the Context based APIs.

Using/Requiring context added a lot of overhead to every Read/Write because we had the channel/mutex brought along with the context.
