### ISSUE TITLE
NATted evnironment test tool: vnet

### ISSUE THREAD

**Issue by enobufs** [pion/transport#13]
## Summary
We need a tool to test ICE / NAT traversal tests.

## Motivation
Testing ICE is HARD. We need a tool to test pion/ice on various types of network configuration.

## Describe alternatives you've considered
We could use [a docker solution](https://github.com/enobufs/nat-traversal-test-using-docker), but the test takes too long and lacks different types of NAT.

## Additional context
Please see [README](https://github.com/pion/transport/blob/feature/vnet/vnet/README.md) under pion/transport/vnet/.

**Comment by enobufs** [comment]
https://github.com/pion/transport/tree/feature/vnet

@hugoArregui @Sean-Der @backkem 
My progress has been slow but the basic framework has been implemented. For pion/ice and pion/stun to be able to switch to vnet, ListenUDP() and Dialer are still missing and I will be implementing those soon, but I would be great to receive early feedback from you guys.

**Comment by Sean-Der** [comment]
That is amazing @enobufs! I am super excited to try this out, reading through it right now.

**Comment by hugoArregui** [comment]
This is amazing! I'm working on the checklist ICE PR, I think we should totally test it with this. Should we collect a list of the different test cases we want to cover so we can help you to develop and test this?

**Comment by enobufs** [comment]
A list of possible test cases will help!
I need to implement STUN server in pion/stun before we start using it... @Sean-Der who do you think the right person for the work would be?

**Comment by Sean-Der** [comment]
We do have [this](https://github.com/pion/stun/blob/master/test/udp_server.go)

**Comment by enobufs** [comment]
Oh nice!! We could the simple STUN server (based on the test code) inside vnet for now.

**Comment by enobufs** [comment]
Hmm, it may create a circular reference... can we add stun/server.go (marked as experimental or something)?

**Comment by ernado** [comment]
About simple STUN server:
Feel free to ctrl+c ctrl+v the https://github.com/gortc/stund if it enough

Also, regarding testing of ICE and STUN:
http://mininet.org/
