### ISSUE TITLE
vnet: Introduce interface for vnet.Net

### ISSUE THREAD

**Issue by stv0g** [pion/transport#168]
## Summary

I propose to add an interface for vnet.Net which dependent packages of `vnet.Net` should use (e.g. pion/ice in my use case).

## Motivation

[cunicu](https://github.com/stv0g/cunicu) is user-space daemon to establish Wireguard peer-to-peer connection via ICE.

cunicu needs to provide custom implementations of `net.{Dial,Listen}{UDP,Packet}` in order to attach eBPF filters to the created sockets which filter STUN and let all other traffic pass to a kernel tunnel interface.

See: https://github.com/stv0g/cunicu/blob/master/pkg/proxy/ebpf.go#L43

This allows cunicu to limit itself to handling ICE and stay out of the data path which remains fully in the kernel.

By introducing an interface for `vnet.Net` users could provide custom implementations for most of the functions in the `net` package.

## Describe alternatives you've considered

We are currently providing a custom implementation of `ice.UDPMux` which is already an interface to do the same.

## Additional context

A `ice.UDPMux` is currently only used for host candidates. We cant use this method for relay or reflexive candidates.
See:  https://github.com/pion/ice/issues/400

Also:
- https://github.com/pion/ice/issues/76
- https://github.com/pion/transport/issues/27

**Comment by Sean-Der** [comment]
Yes this would great! I have seen other use cases that would be unblocked by this also.

**Comment by stv0g** [comment]
Also related: https://github.com/pion/transport/issues/27

**Comment by stv0g** [comment]
@Sean-Der Thats great to hear :)

Ideally, I would name that interface identically to the currently existing struct.

However this would break the existing API and hence requires a new major version.
Would this be acceptable?
