### ISSUE TITLE
Add back our custom implemetation of `sync.WaitGroup`

### ISSUE THREAD

**Issue by stv0g** [pion/transport#259]
We have been using a custom implementation of `sync.WaitGroup` to fix a data race in the `PacketConn` code used by `pion/dtls`

See:
- https://github.com/pion/udp/issues/74
- https://github.com/pion/transport/issues/57#issuecomment-1694528604

**Comment by edaniels** [comment]
It looks like sync.WaitGroup is in use in transport for connWG and there's no current issues around it being used, so I'll close this issue for now.
